### ISSUE TITLE
range problem during MF optimization

### ISSUE THREAD

**Issue by Hippozhibos** [MyoHub/myoconverter#28]
I get an error like this:
![image](https://github.com/MyoHub/myoconverter/assets/73272889/b6b70b47-0eac-4bec-8814-e689acb133b0)

so I go and checked the cvt3.xml file and find the muscle parameters are like these:
![image](https://github.com/MyoHub/myoconverter/assets/73272889/bebfa97a-6b0d-4bd0-a926-2e3c4b33b446)

the only difference between the Anconeus and other muscles are 2nd parameter in gainprm and biasprm are negative. It seems like this negative value affected the range, and then generate this error. But how can I fixed it? I also checked the original .osim file, all parameters for Anconeus seems reasonable compared to other muscles. So I wonder if you've ever seen this type of error, and do you have any suggestion what I should do to fix this error?

**Comment by Hippozhibos** [comment]
Another hint is this:

this is how the model looks like in OpenSim:
![image](https://github.com/MyoHub/myoconverter/assets/73272889/3ad0feb2-eb6d-42a8-86a5-cc8fe6b9beed)

but this is how the cvt2.xml looks like in Mujoco:
![f80cb05e06c3324f483c33020c9ac1a](https://github.com/MyoHub/myoconverter/assets/73272889/92ceba90-6e08-4dc5-967a-14f530f3f554)

There are clear discrepancy between .osim model and cvt2.xml. Would that affect the MF optimization process? and why cvt2.xml (and cvt1.xml looks similar with cvt2) has such huge discrepancy with original .osim model? Any suggestion to fix this?

**Comment by HuaweiWang** [comment]
Hi @Hippozhibos

Could you check the tendon slack length of that muscle? My understanding is that the tendon slack length is too large compared to the total muscle-tendon length, which caused the normalized fiber length range to be negative.

In terms of the discrepancy of the converted model. Please look at the limitation page of our [document](https://myoconverter.readthedocs.io/en/latest/limitations.html). My guess is that your model contains nonlinear joint dependency (limitation no. 6) which we cannot handle yet.

**Comment by Hippozhibos** [comment]
Thanks for your reply! @HuaweiWang

I checked the tendon slack length of the muscles. For some of the muscles, yes, the tendon slack length value is too large, and after revising it to a smaller value MyoConverter can process it. But there are still some muscles, even when I set tendon slack length near to zero, I still get the same error. 
![image](https://github.com/MyoHub/myoconverter/assets/73272889/b8fb1137-e2e2-4936-8363-33f6caa8a281)

As to the limitation no.6, I'm sorry I don't really understand what the "nonlinear joint dependency" means. It seems that only occurred in CustomJoints, right? and what shall do to revise it?

And I'll email you the .osim file I used, maybe you can find more error that I made. Most of the parameters of muscles and bones are incorrect, since we are still trying to collect those data.

Thanks again for all your help!

**Comment by HuaweiWang** [comment]
It seems the optimal fiber length is very unrealistic (0.59m). I would suggest making sure all the parameters in osim model are realistic and then performing the conversion. MyoConverter does not have the ability to check/change unrealistic osim model parameters.

As for the nonlinear joint dependency. My suggestion is to remove them from the Osim model first. Then do the conversion. After conversion, you can add to the converted mujoco model manually.

Hope these can help your project!

**Comment by HuaweiWang** [comment]
Close the issue with no further questions related
