### ISSUE TITLE
Pandas/Numpy Compatibility Error: Upgrade Numpy Required

### ISSUE THREAD

**Issue by Ali-Foro** [MyoHub/myoconverter#29]
### Error message: 
```
ImportError: this version of pandas is incompatible with numpy < 1.22.4
your numpy version is 1.21.6.
Please upgrade numpy to >= 1.22.4 to use this pandas version
```
### New Error After Upgrade Attempt:
```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
  https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```
I attempted to upgrade numpy using pip install --upgrade numpy, but encountered the above AttributeError

I'm really stuck on this. Has anyone else encountered this issue? Any help with potential causes or troubleshooting steps would be greatly appreciated.
Thanks in advance!

Environment:
pandas version: [2.1.1]
Python version: [3.10.13]
OS: [macOS]

**Comment by unikkabhi** [comment]
I got the same problem

**Comment by julie1802** [comment]
I got the same issue. We tried Python 3.9,3.10 and 3.11.  However, none of them seams to be compatible with the needed version of opensim and numpy(we also tried updating numpy from 1.21.6 to 1.22.4 and also to 1.26.4).

**Comment by rogervankanten** [comment]
I've created #32 to update numpy (1.23.5) and other packages.
Numpy >= 1.24 is not supported yet because other packages that depend on it are still using aliases like 'np.bool' that were deprecated since version 1.24.
