### ISSUE TITLE
 how to transform the motion trajectory generated by opensim into mujoco for motion

### ISSUE THREAD

**Issue by 2802029572** [MyoHub/myoconverter#34]
Dear Author:
   Hi, I use myoconverter to transform opensim model into mujoco model, please tell me how to transform the motion trajectory generated by opensim into mujoco for motion, thanks!

**Comment by HuaweiWang** [comment]
Hi,

We haven't tried the process that you mentioned. This is more relevent to the MuJoCo simulation platform, in term of what data you can use. Please refer to their document for more information: https://mujoco.readthedocs.io/en/stable/overview.html

Hope it helps!

Best,
Huawei

**Comment by Vittorio-Caggiano** [comment]
@2802029572 use of mot angles (if the mujoco file has the same joint conventions as opensim) can be done by simply transform euler angles to quaternion. This is what is typically done for imitation learning in [myosuite](https://github.com/MyoHub/myosuite)
