### ISSUE TITLE
.mot data generated in opensim to mujoco for use,

### ISSUE THREAD

**Issue by 2802029572** [MyoHub/myoconverter#35]
Hello, I use myoconverter tool to convert the model in opensim to mujoco, at the same time, I also want to import the .mot data generated in opensim to mujoco for use, how should I do it, please is it convenient to give some references, thanks!

**Comment by HuaweiWang** [comment]
Hi,

We haven't tried the process that you mentioned. This is more relevent to the MuJoCo simulation platform, in term of what data you can use. Please refer to their document for more information:  https://mujoco.readthedocs.io/en/stable/overview.html

Hope it helps!

Best,
Huawei
